
local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 3.0
  publish_frequency: 2.0 # HZ, the costmap will publish visualization information
  static_map: false
  rolling_window: true # the local costmap remain center despite robot moving
  width: 3.0 # meter
  height: 3.0
  resolution: 0.05 #(meters/cell) mostly eqaul to static map resolution 

  plugins:
    - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
  
