base_global_planner: "global_planner/GlobalPlanner" #navfn/NavfnROS
base_local_planner: "dwa_local_planner/DWAPlannerROS" #"base_local_planner/TrajectoryPlannerROS" # 
# The rate in Hz at which to run the control loop and
# send velocity commands to the base. 
controller_frequency: 3.0

# How long the planner will wait in seconds 
# in an attempt to find a valid plan 
# before space-clearing operations are performed. 
# 공간 정리 작업이 수행되기 전에 유효한 계획을 찾기 위해 계획자가 몇 초 안에 대기하는 시간.
planner_patience: 3.0

# How long the controller will wait in seconds 
# without receiving a valid control before space-clearing operations are performed. 
# 공간 지우기 작업을 수행하기 전에 컨트롤러가 유효한 컨트롤을 수신하지 않고 몇 초 동안 대기하는 시간.
controller_patience: 10

# Whether or not to enable the move_base recovery behaviors to attempt to clear out space. 
recovery_behavior_enabled: true


# 로봇과의 거리(미터)를 기준으로 
# 지도에서 공간을 확보하려고 할 때 비용 맵에서 장애물이 제거될 거리
# Note, this parameter is only used when the default recovery behaviors are used for move_base. 
conservative_reset_dist: 5.0

# Determines whether or not the robot will attempt an in-place rotation 
# when attempting to clear out space.
clearing_rotation_allowed: true


# Determines whether or not to shutdown the costmaps of the node 
# when move_base is in an inactive state 
shutdown_costmaps: false

# The rate in Hz at which to run the global planning loop
# 주파수가 0.0으로 설정된 경우, 글로벌 플래너는 새 목표가 수신되거나 
# 로컬 플래너가 경로가 차단되었다고 보고할 때만 실행됩니다.
planner_frequency: 0.0

# 복구 동작을 실행하기 전에 계획 재시도를 허용할 횟수
# A value of -1.0 corresponds to an infinite retries. 
max_planning_retries: -1

# 복구 동작을 실행하기 전에 진동할 수 있는 시간(초)입니다. 0.0 값은 무한 시간 초과에 해당합니다.
oscillation_timeout: 0.0
# How far in meters the robot must move to be considered not to be oscillating.
# Moving this far resets the timer counting up to the oscillation_timeout
oscillation_distance: 0.3