scan_filter_chain:
- name: AngularBoundsFilter
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 0.00
    upper_angle: .

- name: AngularBoundsFilter2
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: .0
    upper_angle: .0